# Generated by Django 3.2.3 on 2021-05-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingfield',
            name='key',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
