# Generated by Django 3.2.3 on 2021-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settingfield_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingfield',
            name='key',
            field=models.CharField(max_length=20),
        ),
    ]
