# Generated by Django 3.2.3 on 2021-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=20)),
                ('streamURL', models.URLField(max_length=500)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
