# Generated by Django 3.2.3 on 2021-05-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_alter_ipcamera_streamurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipcamera',
            name='streamURL',
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='record',
            field=models.BooleanField(default=False),
        ),
    ]
